name       : python-webencodings
version    : 0.5.1
release    : 2
source     :
    - https://github.com/gsnedders/python-webencodings/archive/v0.5.1.tar.gz : 082367f568a7812aa5f6922ffe3d9d027cd83829dc32bcaac4c874eeed618000
license    : BSD-3-Clause
component  : programming.python
summary    : Character encoding for the web.
description: |
    Character encoding for the web.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
